//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalalidham.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMultiImage
    {
        public int Id { get; set; }
        public int ImageTitleId { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
